/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      // Use CSS variables so we can control colors at runtime and keep
      // consistency between custom CSS and Tailwind utilities.
      colors: {
        'primary': 'var(--color-primary)',
        'secondary': 'var(--color-secondary)',
        'brand': 'var(--color-primary)',
        'accent': 'var(--color-secondary)'
      ,
      // Provide mappings for common blue/indigo utilities used across the app
      // Expose explicit shades so classes like `bg-blue-600` and `bg-indigo-700`
      // are generated by Tailwind and map to our CSS variables.
      blue: {
        600: 'var(--color-blue-600)',
      },
      indigo: {
        600: 'var(--color-indigo-600)',
        700: 'var(--color-indigo-700)',
        800: 'var(--color-indigo-800)'
      }
      }
    },
  },
  plugins: [],
}
