services:
  - type: web
    name: entrenapro-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    # No incluir DATABASE_URL aquí; configúrala en la UI de Render o usando secrets

jobs:
  - name: create-tables
    type: run
    env: python
    command: python backend/manage.py create_tables
